-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "breeze_cursors")
hl.env("XCURSOR_SIZE", "20")

-- Settings
hl.config({
    decoration = {
        rounding = 5,
        shadow = {
            enabled = false,
        },
    },
    general = {
        border_size = 2,
        col = {
            active_border = {
                colors = {"rgba(f0b5dcff)", "rgba(ffb3b4ff)"},
            },
            inactive_border = {
                colors = {"rgba(381130ff)", "rgba(4b2241ff)"},
            },
        },
        gaps_in = 1,
        gaps_out = 5,
    },
})
